// <auto-generated />
using System;
using CrudConteiners.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudConteiners.Migrations
{
    [DbContext(typeof(CrudConteinerContext))]
    [Migration("20230901041326_migrationV2RequiredClient")]
    partial class migrationV2RequiredClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrudConteiners.Models.Conteiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Categoria")
                        .HasColumnType("INT");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("NumeroConteiner")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<int>("TipoConteiner")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("Conteiners");
                });

            modelBuilder.Entity("CrudConteiners.Models.Movimentacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("DATETIME");

                    b.Property<int>("ID_Conteiner")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("ID_Conteiner");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("CrudConteiners.Models.Movimentacoes", b =>
                {
                    b.HasOne("CrudConteiners.Models.Conteiner", "Conteiner")
                        .WithMany()
                        .HasForeignKey("ID_Conteiner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteiner");
                });
#pragma warning restore 612, 618
        }
    }
}
